users/models.py
from wsgiref.validate import validator
from extensions import db

class user(db.Model):
    __tablename__ = 'user_model'

    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(20), nullable=False)

    def __repr__(self):
        return f'<user {self.full_name}>'

users/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, StringField, ValidationError
from wtforms.validators import DataRequired, Length


class UserRegistrationForm(FlaskForm):
   email = EmailField("Email", validators=[])
   full_name = StringField('Full Name', validators=[DataRequired(), Length(0, 40)])
   password = PasswordField("Password")
   password2 = PasswordField("Confirm Password")

   def validate_password(self, field):
        password2 = self.data["password2"]
        if password2 != field.data:
            raise ValidationError("Both passwords are not matched !!!")

users/__init__.py
from flask import Blueprint

users = Blueprint("users", __name__, static_folder="static", template_folder="templates")

from . import routes

users/routes.py
from flask import Blueprint, redirect, render_template, request, url_for
from .forms import UserRegistrationForm
from . import users
from .models import user
from extensions import db


@users.route("/")
def user_list():
    users = user.query.all()
    return render_template("users/user_list.html", users=users)


@users.route("create/", methods=["GET", "POST"])
def user_create():
    form = UserRegistrationForm()
    if request.method == "GET":
        return render_template("users/user_form.html", form=form)
    else:
        if form.validate_on_submit():
            email = form.email.data
            full_name = form.full_name.data
            password = form.password.data
            
            try:
                user_obj = user(
                    full_name=full_name,
                    email=email,
                    password=password,
                )

                db.session.add(user_obj)
                db.session.commit()
                
            except Exception as e:
                db.session.rollback()
                print(f"Error: {e}")
        else:
            print(f"==>> form: {form.errors}")
            return render_template("users/user_form.html", form=form)

        return redirect(url_for("users.user_list"))


@users.route("update/<int:user_id>", methods=["GET", "POST"])
def user_update(user_id):
    user_obj = user.query.get_or_404(user_id)
    form = UserRegistrationForm(obj = user_obj)

    if request.method == "GET":
        return render_template("users/user_form.html", form=form, user=user_obj)
    else:
        if form.validate_on_submit():
            form.populate_obj(user_obj)
            
            try:
                db.session.commit()
                return redirect(url_for("users.user_list"))
                
            except Exception as e:
                db.session.rollback()
                print(f"Error: {e}")
        else:
            print(f"==>> form: {form.errors}")
            return render_template("users/user_form.html", form=form, user=user_obj)

    return render_template("users/user_form.html", form=form, user=user_obj)

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <h2>Dashboard </h2>
</body>
</html>

templates/users/user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% if user %}
        Update User
        {% else %}
        New User
        {% endif %}
    </title>
</head>
<body>
    
    {% if user %}
    <h1>Update User</h1>
    {% else %}
    <h1>Add New User</h1>
    {% endif %}

    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.full_name.label }}
            {{ form.full_name }}

            {% if form.full_name.errors %}
                {% for error in form.full_name.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
        </div>
        <div>
            {{ form.email.label }}
            {{ form.email }}

            {% if form.email.errors %}
                {% for error in form.email.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
        </div>
        <div>
            {{ form.password.label }}
            {{ form.password }}

            {% if form.password.errors %}
                {% for error in form.password.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
        </div>
        <div>
            {{ form.password2.label }}
            {{ form.password2 }}

            {% if form.password2.errors %}
                {% for error in form.password2.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
        </div>
        <br/>
        <div>
            <button type="submit">{% if not user %}Add {% else %} Update{% endif %}</button>
        </div>
    </form>
</body>
</html>

templates/users/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
</head>
<body>
    <div>
        <div>
            <h3>Users</h3>
        </div>
        <div>
            <a href="{{ url_for('users.user_create') }}"><button>Create User</button></a>
        </div>
        <table border="1">
            <thead>
                <tr>
                    <th>Sr. No.</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                
                {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.full_name|title }}</td>
                    <td>{{ user.email }}</td>
                    <td>
                        <a href="{{ url_for('users.user_update', user_id=user.id) }}">Update</a>
                    </td>
                </tr>
                {% endfor %}
                    
            </tbody>
        </table>
    </div>
</body>
</html>